# Generated by Django 5.2.17 on 2026-09-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='category',
            new_name='position',
        ),
    ]
